import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import NewsCard from "../../components/card/NewsCard";
import PopularCard from "../../components/card/PopularCard";
import Loding from "../../components/loading/Loding";
import { instance } from "../../utils/axios/axios_interceptor";

export default function Category({ info }) {
  const [isLoading, setIsLoading] = useState(true);

  const router = useRouter();
  const { category } = router.query;

  let { limit: uLimit, page: uPage } = router.query;

  let page = uPage ? Number(uPage) : 1;
  let limit = uLimit ? Number(uLimit) : 20;

  useEffect(() => {
    setIsLoading(false);
  }, []);

  let pageCount;
  if (info) {
    pageCount = Math.ceil(info.total_post / limit);
  }

  const nextPage = () => {
    if (page < pageCount) {
      router.push(`/?limit=${limit}&page=${page + 1}`);
    }
  };

  const previousPage = () => {
    if (page > 1) {
      router.push(`/?limit=${limit}&page=${page - 1}`);
    }
  };

  if (isLoading) {
    return (
      <>
        <Loding />
      </>
    );
  }

  return (
    <div className=" w-full min-h-screen">
      <Head>
        <title>blog app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://localhost:4000" />
      </Head>
      <main>
        <div className=" pt-40 w-[1239px] min-h-[120vh] xl:w-full lg:w-full mdl:w-full mx-auto xl:px-3 lg:px-2 lg:pt-40 md:px-2 md:pt-28 sm:px-1 sm:pt-32">
          <div className="ml-3 xl:ml-6 lg:ml-1 md:ml-5 ms:ml-1 pb-10">
            <div className=" flex items-center pb-3 xs:flex-wrap break-all">
              <Link
                href={"/"}
                className=" text-xs capitalize bg-black text-white hover:text-gray-300  rounded-[3px] p-[3px] break-all"
              >
                home
              </Link>
              <span className=" ml-1">
                <svg
                  className="fill-current h-4 w-4 -rotate-90  text-gray-400"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                >
                  <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                </svg>
              </span>
              <span className=" text-xs capitalize text-gray-400 break-all">
                {category}
              </span>
            </div>
            <h1 className=" font-bold text-3xl uppercase break-all">
              {category}
            </h1>
          </div>
          <div className=" flex mdl:flex-col">
            <div className="  w-[850px] pr-6 xl:px-3 lg:px-2  mdl:w-full  mdl:px-6 ms:px-2">
              <div className=" flex items-center justify-center gap-4 flex-wrap ms:flex-col ">
                {info && info?.posts?.length === 0 && (
                  <p className=" capitalize text-center">no post found</p>
                )}
                {info &&
                  info?.posts?.map((post) => (
                    <NewsCard
                      key={post.id}
                      href={`/posts/${post?.slug}`}
                      data={post}
                    />
                  ))}
              </div>
              {info && info?.posts?.length !== 0 && (
                <div className=" text-center my-10">
                  <button
                    type="button"
                    onClick={previousPage}
                    className=" w-28 mx-6 text-sm outline-none capitalize hover:text-white hover:bg-sky-500 py-1 px-2 text-gray-500 border"
                  >
                    previous
                  </button>
                  <button
                    type="button"
                    onClick={nextPage}
                    className=" w-28 mx-6 text-sm outline-none capitalize hover:text-white hover:bg-sky-500 py-1 px-2 text-gray-500 border"
                  >
                    next
                  </button>
                </div>
              )}
            </div>

            <div className=" w-[380px] h-[600px] overflow-hidden  mdl:w-full shadow-[0_0_6px_rgb(0,0,0,0.12)] rounded-lg mdl:mt-8">
              <div className=" w-full mt-5 py-4 ">
                <h2 className="  text-center pb-5 text-3xl text-gray-700 ms:text-2xl border-b ms:break-all">
                  Populer Posts
                </h2>
                <div className="">
                  {info && info?.popular_posts?.length === 0 && (
                    <p className=" capitalize text-center">no post found</p>
                  )}
                  {info &&
                    info?.popular_posts?.map((post) => (
                      <PopularCard
                        key={post.id}
                        href={`/posts/${post?.slug}`}
                        data={post}
                      />
                    ))}
                </div>
              </div>
            </div>
          </div>
        </div>{" "}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { category, limit, page } = context.query;

  let info;
  try {
    const numberOfPostlimit = limit ? parseInt(limit) : 20;
    const numberOfPage = page ? parseInt(page) : 1;
    const { data } = await instance.get(
      `/api/v1/get/all/post/with/recent/post?limit=${numberOfPostlimit}&page=${numberOfPage}&category=${category}`
    );
    info = data.info;
  } catch (error) {
    info = {};
  }
  return {
    props: {
      info,
    },
  };
}
